name: "Gemini Live Bridge"
description: "A high-performance bridge service connecting Home Assistant Voice to the Gemini Live API."
version: "1.1.3"
slug: "gemini_bridge"
init: false
map:
  - config:rw
hassio_api: true
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  GEMINI_API_KEY: ""
  GEMINI_MODEL: "models/gemini-2.5-flash-live-preview"
  GEMINI_VOICE: "Puck"
  HA_URL: "http://supervisor/core"
  HA_TOKEN: ""
  WAKE_WORD: "hey_jarvis"
  CUSTOM_WAKE_WORD_DIR: "/config/wakewords"
  LOG_LEVEL: "INFO"
schema:
  GEMINI_API_KEY: "password"
  GEMINI_MODEL: "str"
  GEMINI_VOICE: "str"
  HA_URL: "str"
  HA_TOKEN: "password"
  WAKE_WORD: "str"
  CUSTOM_WAKE_WORD_DIR: "str"
  LOG_LEVEL: "match(^DEBUG|INFO|WARNING|ERROR|CRITICAL$)"
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: "Websocket Bridge API"
