substitutions:
  name: "gemini-atom-echo"
  friendly_name: "Gemini Atom Echo"
  websocket_url: "ws://10.3.0.41:8000/ws" # IP deiner Gemini Bridge hier eintragen!

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  includes:
    - gemini_websocket.h
  on_boot:
    priority: -100
    then:
      - lambda: |-
          auto gemini_client = new GeminiWebSocketClient("${websocket_url}", id(echo_mic), id(echo_speaker));
          gemini_client->setup();

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

# WLAN Konfiguration
wifi:
  ssid: "HEPTACOM UID_IoT"
  password: "5yeh)SRM"
  reboot_timeout: 0s

# API & OTA für ESPHome
api:
  reboot_timeout: 0s
ota:

# Status LED des Atom Echo
light:
  - platform: fastled_clockless
    chipset: WS2812B
    pin: GPIO27
    num_leds: 1
    rgb_order: GRB
    name: "Atom Echo LED"

i2s_audio:
  i2s_lrclk_pin: GPIO33
  i2s_bclk_pin: GPIO19

microphone:
  - platform: i2s_audio
    id: echo_mic
    i2s_din_pin: GPIO23
    adc_type: external
    pdm: true

speaker:
  - platform: i2s_audio
    id: echo_speaker
    dac_type: external
    i2s_dout_pin: GPIO22
    mode: mono
